services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Reelworx\RxShariff\:
    resource: '../Classes/*'
    exclude: '../Classes/Shariff/*'

  Heise\Shariff\:
    resource: '../Classes/Shariff/*'

